// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameUserInfo = "t_user_info"

// UserInfo mapped from table <t_user_info>
type UserInfo struct {
	ID       int32  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Gender   string `gorm:"column:gender;not null" json:"gender"`
	Birthday string `gorm:"column:birthday;not null" json:"birthday"`
}

// TableName UserInfo's table name
func (*UserInfo) TableName() string {
	return TableNameUserInfo
}
